# Generated by Django 4.1 on 2022-08-28 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('site_tree_id', models.CharField(max_length=255)),
                ('location_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('species', models.URLField()),
                ('diameter_at_breast_height', models.PositiveIntegerField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.site')),
            ],
            options={
                'unique_together': {('site', 'site_tree_id')},
            },
        ),
    ]
